clear;
clc;
close all;

%% ============================================================
% CONFIGURATION
% ============================================================

modelName = 'mi_modelo_dtmf';

outputDir = fullfile(pwd, 'simulation_results');

if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

% DTMF parameters
fLow = 770;             % Hz
fHigh = 1336;            % Hz

% Sampling parameters
sampleRate = 8000;       % Hz
Ts = 1 / sampleRate;

% Simulation duration
stopTime = 0.25;         % seconds


%% ============================================================
% CREATE SIMULINK MODEL
% ============================================================

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

new_system(modelName);
open_system(modelName);


%% ============================================================
% ADD BLOCKS
% ============================================================

add_block( ...
    'simulink/Sources/Sine Wave', ...
    [modelName '/Frecuencia_Baja'], ...
    'Position', [50 50 100 90]);

add_block( ...
    'simulink/Sources/Sine Wave', ...
    [modelName '/Frecuencia_Alta'], ...
    'Position', [50 130 100 170]);

add_block( ...
    'simulink/Math Operations/Add', ...
    [modelName '/Sumador'], ...
    'Position', [160 90 190 130]);

add_block( ...
    'simulink/Discrete/Zero-Order Hold', ...
    [modelName '/Canal_Muestreo'], ...
    'Position', [240 90 290 130]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [modelName '/Datos_DTMF'], ...
    'Position', [360 90 460 120]);


%% ============================================================
% CONFIGURE SINE WAVES
% ============================================================

set_param( ...
    [modelName '/Frecuencia_Baja'], ...
    'SineType', 'Time based', ...
    'Frequency', sprintf('2*pi*%g', fLow), ...
    'SampleTime', num2str(Ts));

set_param( ...
    [modelName '/Frecuencia_Alta'], ...
    'SineType', 'Time based', ...
    'Frequency', sprintf('2*pi*%g', fHigh), ...
    'SampleTime', num2str(Ts));


%% ============================================================
% CONFIGURE SAMPLE/HOLD
% ============================================================

set_param( ...
    [modelName '/Canal_Muestreo'], ...
    'SampleTime', num2str(Ts));


%% ============================================================
% CONFIGURE TO WORKSPACE
% ============================================================

set_param( ...
    [modelName '/Datos_DTMF'], ...
    'VariableName', 'senal_dtmf', ...
    'SaveFormat', 'Timeseries');


%% ============================================================
% CONNECT BLOCKS
% ============================================================

add_line( ...
    modelName, ...
    'Frecuencia_Baja/1', ...
    'Sumador/1', ...
    'autorouting', 'on');

add_line( ...
    modelName, ...
    'Frecuencia_Alta/1', ...
    'Sumador/2', ...
    'autorouting', 'on');

add_line( ...
    modelName, ...
    'Sumador/1', ...
    'Canal_Muestreo/1', ...
    'autorouting', 'on');

add_line( ...
    modelName, ...
    'Canal_Muestreo/1', ...
    'Datos_DTMF/1', ...
    'autorouting', 'on');


%% ============================================================
% SIMULATION
% ============================================================

set_param( ...
    modelName, ...
    'StopTime', num2str(stopTime));

save_system(modelName);

simOut = sim(modelName);

%% ============================================================
% GET SIMULATION DATA
% ============================================================


senal_dtmf = simOut.get('senal_dtmf');

if isempty(senal_dtmf)
    error('The simulation did not return "senal_dtmf".');
end

t = senal_dtmf.Time;
x = senal_dtmf.Data;


%% ============================================================
% GRAPH 1: TIME DOMAIN - ZOOM
% ============================================================

fig1 = figure('Visible', 'off');

plot(t, x, 'LineWidth', 1);

grid on;

xlabel('Time [s]');
ylabel('Amplitude');

title(sprintf( ...
    'DTMF Signal - Time Domain (%d Hz + %d Hz)', ...
    fLow, fHigh));

subtitle(sprintf( ...
    'Sampling rate: %d Hz | Duration: %.3f s', ...
    sampleRate, stopTime));

xlim([0 min(stopTime, 0.03)]);

timeGraph = fullfile( ...
    outputDir, ...
    sprintf( ...
    'dtmf_time_domain_%dHz_%dHz.png', ...
    fLow, fHigh));

exportgraphics( ...
    fig1, ...
    timeGraph, ...
    'Resolution', 200);

close(fig1);


%% ============================================================
% GRAPH 2: COMPLETE TIME DOMAIN
% ============================================================

fig2 = figure('Visible', 'off');

plot(t, x, 'LineWidth', 1);

grid on;

xlabel('Time [s]');
ylabel('Amplitude');

title('DTMF Signal - Complete Simulation');

subtitle(sprintf( ...
    '%d Hz + %d Hz | Fs = %d Hz | Duration = %.3f s', ...
    fLow, fHigh, sampleRate, stopTime));

fullTimeGraph = fullfile( ...
    outputDir, ...
    sprintf( ...
    'dtmf_complete_signal_%dHz_%dHz.png', ...
    fLow, fHigh));

exportgraphics( ...
    fig2, ...
    fullTimeGraph, ...
    'Resolution', 200);

close(fig2);


%% ============================================================
% GRAPH 3: FREQUENCY DOMAIN / FFT
% ============================================================

N = length(x);

Y = fft(x);

P2 = abs(Y / N);

P1 = P2(1:floor(N / 2) + 1);

P1(2:end-1) = 2 * P1(2:end-1);

f = sampleRate * ...
    (0:floor(N / 2)) / N;


fig3 = figure('Visible', 'off');

plot(f, P1, 'LineWidth', 1);

grid on;

xlabel('Frequency [Hz]');
ylabel('Magnitude');

title('DTMF Signal - Frequency Spectrum');

subtitle(sprintf( ...
    'Expected tones: %d Hz and %d Hz | Fs = %d Hz', ...
    fLow, fHigh, sampleRate));

xlim([0 2000]);

frequencyGraph = fullfile( ...
    outputDir, ...
    sprintf( ...
    'dtmf_frequency_spectrum_%dHz_%dHz.png', ...
    fLow, fHigh));

exportgraphics( ...
    fig3, ...
    frequencyGraph, ...
    'Resolution', 200);

close(fig3);


%% ============================================================
% GRAPH 4: ZOOMED FREQUENCY SPECTRUM
% ============================================================

fig4 = figure('Visible', 'off');

plot(f, P1, 'LineWidth', 1);

grid on;

xlabel('Frequency [Hz]');
ylabel('Magnitude');

title('DTMF Signal - Frequency Components');

subtitle(sprintf( ...
    'Low tone = %d Hz | High tone = %d Hz', ...
    fLow, fHigh));

xlim([500 1600]);

frequencyZoomGraph = fullfile( ...
    outputDir, ...
    sprintf( ...
    'dtmf_frequency_components_%dHz_%dHz.png', ...
    fLow, fHigh));

exportgraphics( ...
    fig4, ...
    frequencyZoomGraph, ...
    'Resolution', 200);

close(fig4);


%% ============================================================
% FFT PEAK DETECTION
% ============================================================

[peakValues, peakLocations] = findpeaks( ...
    P1, ...
    f, ...
    'MinPeakHeight', 0.5);

% Find closest peaks to theoretical DTMF frequencies

[~, lowIndex] = ...
    min(abs(peakLocations - fLow));

[~, highIndex] = ...
    min(abs(peakLocations - fHigh));

detectedLow = peakLocations(lowIndex);
detectedHigh = peakLocations(highIndex);

lowError = ...
    abs(detectedLow - fLow) / fLow * 100;

highError = ...
    abs(detectedHigh - fHigh) / fHigh * 100;


%% ============================================================
% METADATA
% ============================================================

metadata = struct();

metadata.simulation = struct( ...
    'model', modelName, ...
    'description', ...
        'DTMF dual-tone signal generation and sampling simulation', ...
    'duration_seconds', stopTime, ...
    'sample_rate_hz', sampleRate, ...
    'sample_period_seconds', Ts);

metadata.input_signals = struct( ...
    'low_frequency_hz', fLow, ...
    'high_frequency_hz', fHigh, ...
    'signal_type', 'Two sinusoidal signals summed together', ...
    'low_signal_amplitude', 1, ...
    'high_signal_amplitude', 1);

metadata.frequency_analysis = struct( ...
    'expected_low_frequency_hz', fLow, ...
    'expected_high_frequency_hz', fHigh, ...
    'detected_low_frequency_hz', detectedLow, ...
    'detected_high_frequency_hz', detectedHigh, ...
    'low_frequency_error_percent', lowError, ...
    'high_frequency_error_percent', highError, ...
    'fft_frequency_resolution_hz', sampleRate / N, ...
    'nyquist_frequency_hz', sampleRate / 2);

metadata.expected_behavior = { ...
    sprintf( ...
        'The time-domain signal should contain two sinusoidal components at %d Hz and %d Hz.', ...
        fLow, fHigh), ...
    sprintf( ...
        'The FFT should contain dominant peaks near %d Hz and %d Hz.', ...
        fLow, fHigh), ...
    'No significant frequency components should exist outside the two dominant DTMF tones.', ...
    'The sampling frequency of 8000 Hz provides a Nyquist frequency of 4000 Hz.', ...
    'The Zero-Order Hold represents the sampling/channel stage.' ...
    };

metadata.graphs = struct( ...
    'time_domain_zoom', timeGraph, ...
    'complete_time_domain', fullTimeGraph, ...
    'frequency_spectrum', frequencyGraph, ...
    'frequency_components_zoom', frequencyZoomGraph);

metadata.graph_descriptions = { ...

    sprintf( ...
        'dtmf_time_domain_%dHz_%dHz.png: Zoomed time-domain view of the first 30 ms of the DTMF signal. The waveform is the sum of two sinusoidal signals at %d Hz and %d Hz.', ...
        fLow, fHigh, fLow, fHigh), ...

    sprintf( ...
        'dtmf_complete_signal_%dHz_%dHz.png: Complete time-domain simulation lasting %.3f seconds. Shows the entire sampled DTMF waveform.', ...
        fLow, fHigh, stopTime), ...

    sprintf( ...
        'dtmf_frequency_spectrum_%dHz_%dHz.png: FFT spectrum from 0 to 2000 Hz. The two dominant components should occur at approximately %d Hz and %d Hz.', ...
        fLow, fHigh, fLow, fHigh), ...

    sprintf( ...
        'dtmf_frequency_components_%dHz_%dHz.png: Zoomed FFT spectrum from 500 to 1600 Hz, focusing on the expected DTMF frequency components at %d Hz and %d Hz.', ...
        fLow, fHigh, fLow, fHigh) ...
    };

metadata.analysis_notes = { ...
    sprintf('Expected low-frequency component: %d Hz.', fLow), ...
    sprintf('Expected high-frequency component: %d Hz.', fHigh), ...
    sprintf('Detected low-frequency component: %.2f Hz.', detectedLow), ...
    sprintf('Detected high-frequency component: %.2f Hz.', detectedHigh), ...
    sprintf('Low-frequency detection error: %.4f%%.', lowError), ...
    sprintf('High-frequency detection error: %.4f%%.', highError), ...
    sprintf('Sampling frequency: %d Hz.', sampleRate), ...
    sprintf('Nyquist frequency: %d Hz.', sampleRate / 2), ...
    sprintf('FFT frequency resolution: %.4f Hz.', sampleRate / N), ...
    'The spectrum should show two dominant peaks corresponding to the DTMF tones.', ...
    'Additional significant peaks may indicate distortion, spectral leakage, numerical artifacts, or unintended signal components.' ...
    };


%% ============================================================
% WRITE JSON METADATA
% ============================================================

jsonFile = fullfile( ...
    outputDir, ...
    'simulation_metadata.json');

jsonText = jsonencode( ...
    metadata, ...
    'PrettyPrint', true);

fid = fopen(jsonFile, 'w');

if fid == -1
    error('Could not create metadata file.');
end

fprintf(fid, '%s', jsonText);

fclose(fid);


%% ============================================================
% FINISHED
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('SIMULATION COMPLETED\n');
fprintf('============================================\n');

fprintf('\nResults directory:\n%s\n', outputDir);

fprintf('\nExpected frequencies:\n');
fprintf('  Low : %d Hz\n', fLow);
fprintf('  High: %d Hz\n', fHigh);

fprintf('\nDetected frequencies:\n');
fprintf('  Low : %.2f Hz\n', detectedLow);
fprintf('  High: %.2f Hz\n', detectedHigh);

fprintf('\nDetection errors:\n');
fprintf('  Low : %.4f %%\n', lowError);
fprintf('  High: %.4f %%\n', highError);

fprintf('\nGenerated files:\n');
fprintf('  %s\n', timeGraph);
fprintf('  %s\n', fullTimeGraph);
fprintf('  %s\n', frequencyGraph);
fprintf('  %s\n', frequencyZoomGraph);
fprintf('  %s\n', jsonFile);